services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - ./src:/app/src
    environment:
      - CREATE_TABLE=y
      - PERSISTENCE_MODULE=eventsourcing.postgres
      - POSTGRES_DBNAME=fastapi_eventsourcing
      - POSTGRES_HOST=db
      - POSTGRES_POOL_SIZE=5
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:16-alpine
    volumes:
      - .postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi_eventsourcing
    ports:
      - "5432:5432"
    restart: on-failure
